### PR TITLE
Add Constructor Names

### LINKED ISSUE #750: Rule of type i cannot be applied to entity of type i
SUSHI emits the error `Rule of type i cannot be applied to entity of type i` in some cases.  This is quite cryptic.

Reproduce here: https://fshschool.org/FSHOnline/#/share/2O8g9pZ

This is a valid error -- but the error message is not helpful.  To fix the actual error, use a `^` on the rules that start with `expansion`.

### PR DESCRIPTION
**Pull request by jafeltra**
This PR fixes #750.

It turns out that this issue only showed up in FSH Online because we were using `constructor.name` in our error message, and the constructor names are minimized when we build FSH Online for production. I couldn't find a way to avoid this happening in the built code, so I decided to implement this change in SUSHI. This adds a string `constructorName` to each of the rules and entities that are used in the error message. This shouldn't change how SUSHI works, but should let the error message be correct when we get it in FSH Online. The linked issue has an example of how to replicate the error in SUSHI and FSH Online.

### CODE REVIEW

**Review by ngfreiter — COMMENTED** [review]
This looks good to me!

**Review by ngfreiter — DISMISSED** [review]
Oops I commented instead of approving.

**Review by cmoesel — CHANGES_REQUESTED** [review]
I think this makes sense, but I'd like for the `constructorName` properties to be `readonly` -- because they should never change, right?

**Comment by jafeltra** [comment]
> I think this makes sense, but I'd like for the `constructorName` properties to be `readonly` -- because they should never change, right?

I think that makes sense, but the only slight caveat is that not every `constructorName` can be `readonly`. The ones that are set on classes that are then extended later on can't be `readonly` because then the children can't set their own. Does it make sense to add `readonly` to some, like `CardRule` and `AssignmentRule`, but not on others, like `Rule` and `ValueSetComponentRule`?

**Comment by cmoesel** [comment]
> I think that makes sense, but the only slight caveat is that not every `constructorName` can be `readonly`.

Ah shoot.  I thought TypeScript might allow a child class to set an inherited `readonly` property on instantiation.  Apparently not. I _think_ I'd still rather have it be `readonly` where it can be, but I'm definitely less sure now.

How do you feel about using `getter` functions instead? This makes it effectively read-only, but also allows child classes to override it:
```ts
get constructorName() {
    return 'Rule';
}
```
and you still access it exactly the same way as if it were a normal property...

**Comment by jafeltra** [comment]
> How do you feel about using `getter` functions instead?

I actually considered this approach and started out with it. I talked with @mint-thompson about potentially using an abstract field and when that didn't work out either, I guess I never went back. I'd be good with a `getter`!

**Comment by jafeltra** [comment]
I was testing this out on a fork to make sure this change fixed the issue in the FSH Online production build, but something seems to be failing. I want to make sure that works before merging this.

**Comment by jafeltra** [comment]
Okay false alarm! Something must have been out of sync because I re-packed this branch and used it in a FSH Online fork and the cryptic error message is no longer cryptic. I think this should be set for re-review @ngfreiter and @cmoesel. 

Also, the page it's built at is https://jafeltra.github.io/FSHOnline/#/ if you want to see the no-longer-cryptic error message.

**Review by ngfreiter — APPROVED** [review]
Tested it out, and didn't look cryptic to me 👍 .

**Review by cmoesel — APPROVED** [review]
Let's do this!

**Pull request merged**
