### PR TITLE
Configuration-based IGExporter integration tests

### PR DESCRIPTION
**Pull request by mint-thompson**
Completes task [CIMPL-361](https://standardhealthrecord.atlassian.net/browse/CIMPL-361)

These tests begin with reading in configuration from a yaml file and test to make sure that expected default and configured content is produced in output files. Existing yaml files are used in these tests.

### CODE REVIEW

**Comment by ngfreiter** [comment]
> The one odd thing I noticed is that there are info/error messages logging in my terminal. Is that normal and I'm just blanking? Or are these new to these tests? I feel like they're new, but I might be forgetting something obvious.

I'm also seeing the logs! Should've ran the tests locally, now I will continue to have GitHub Actions trust issues.

**Comment by mint-thompson** [comment]
Correct: there are lots of errors getting logged due to missing files (and there are tests for these messages in `IGExporter.IG.test.ts`), since the tests don't actually load any of the files specified in the configuration.

**Comment by cmoesel** [comment]
Can you load the logger spy to suppress the logging messages when the tests get run?

**Comment by ngfreiter** [comment]
I think though we don't want the logs to be outputted to the terminal when we run `npm run test`. And in this case they do. I believe it is because logger isn't loaded

**Pull request merged**
