### PR TITLE
Assign FSH Code or Reference to CodeableReference element

### PR DESCRIPTION
**Pull request by mint-thompson**
Completes task [CIMPL-1220](https://standardhealthrecord.atlassian.net/browse/CIMPL-1220).

When writing an assignment rule, if the path refers to a CodeableReference element, the value may be a FshCode or FshReference. The value will be applied to the element's concept or reference child element, respectively. It is possible to have two rules with the same CodeableReference path if one assigns a FshCode and the other assigns a FshReference.

I ran a full regression with these changes, and there were no differences in any of the outputs.

### CODE REVIEW

**Review by jafeltra — DISMISSED** [review]
This makes sense to me! The code looks good, and the tests cover everything that I tested locally.

**Review by cmoesel — CHANGES_REQUESTED** [review]
This is great. Your chosen approach for the challenge that we discussed came out very clean. I like it! I asked for one thing related to the tests...

**Review by jafeltra — APPROVED** [review]
I still approve.

**Review by cmoesel — APPROVED** [review]
Approved!

**Pull request merged**
