### PR TITLE
Correct grammar in snapshot missing message

### PR DESCRIPTION
**Pull request by vadi2**

### CODE REVIEW

**Review by vadi2 — COMMENTED** [review]
It's noticeable if you copy/paste the error message into the Chrome browser - their new spellcheck detection picks it up.

**Comment by jafeltra** [comment]
@vadi2 thanks for the PR! This is a nice, simple fix.

I ran the automated checks, and it looks like this is failing the check that runs the unit tests. It looks like [this test](https://github.com/FHIR/sushi/blob/master/test/fhirtypes/StructureDefinition.test.ts#L113-L119) in `test/fhirtypes/StructureDefinition.test.ts` is failing because the new wording is not reflected in the expected text. You can run the tests by running `npm run test`, which should show this test failing. You can also run `npm run check` in order to run the equivalent checks that will be run on the PR, which includes the unit tests, a linting check, and a check for the formatting defined by prettier.

Once that test is fixed, this PR looks good to me. Our team requires two reviews on PRs, so someone else from our team will review it as well.

**Comment by vadi2** [comment]
@jafeltra sure, done!

I edited the file online using github.dev for convenience, I hope the tests are fine now though.

**Review by jafeltra — APPROVED** [review]
Thanks for updating the test! The checks pass, so this looks good to me.

Once another reviewer reviews and approves, we'll merge this in and it will get included in the next release.

**Review by cmoesel — APPROVED** [review]
Thanks @vadi2!

**Pull request merged**
