### PR TITLE
No snapshot

### PR DESCRIPTION
**Pull request by ngfreiter**
This PR stops snapshots from being generated by default. To generate snapshots, the user can use the `-s` or `--snapshot` flag.

My method for testing that this doesn't cause issues in the IG publisher was to run the IG publisher using output both with and without snapshots. I then compared the generated JSON output that the IG publisher created, and looked for any major divergence that wasn't just something like a changed timestamp. This was manual and not super efficient, so if any reviewers have a better way let me know what worked.

### CODE REVIEW

**Comment by cmoesel** [comment]
What FSH did you run this test on?  Random sample FSH, fsh-mcode, or something else?

**Comment by ngfreiter** [comment]
fsh-mcode for me.

**Comment by cmoesel** [comment]
I was hoping you would say that!

**Comment by jafeltra** [comment]
I did notice one additional thing after I had approved that I just wanted to double check on. When comparing the generated files `StructureDefinition-mcode-cancer-disease-status.json` in `output`, I noticed there were a couple differences between what was generated on master and what was generated on this branch. They don't seem too harmful, but I'm not entirely sure where/how they were changed, so I wanted to ask. The only difference in the corresponding SD in `input` is the missing `snapshot` on this branch.

I can also attach the two files if that's easiest for anyone.

**Comment by ngfreiter** [comment]
At least some of these changes do seem to be positive changes. For example, the link http://hl7.org/fhir/us/mcode/extensibility.html is now http://hl7.org/fhir/R4/extensibility.html, changing it from a broken link into one that works.

**Pull request merged**
