### PR TITLE
Update the publisher scripts location

### PR DESCRIPTION
**Pull request by ngfreiter**
Fixes https://github.com/FHIR/sushi/issues/718 by updating `sushi --init` to look in the new location for the IG Publisher scripts, which is this URL: https://github.com/HL7/ig-publisher-scripts.

For testing, I think just running `sushi --init`, making sure the scripts download and can then be run to generate the simple example IG is sufficient.

### CODE REVIEW

**Review by cmoesel — CHANGES_REQUESTED** [review]
GitHub must employ some magic to make this work, because that HL7 project does not have a `master` branch -- it uses the new `main` branch naming scheme: https://github.com/HL7/ig-publisher-scripts/branches

Let's avoid magic and go w/ `main`.

**Review by julianxcarter — DISMISSED** [review]
Apart from Chris's comment about changing the branch name within the url, I'm gonna move forward and approve this since it's working well for me now (and I assume it will after the change). Nice work!

**Comment by ngfreiter** [comment]
> GitHub must employ some magic to make this work, because that HL7 project does not have a `master` branch -- it uses the new `main` branch naming scheme: https://github.com/HL7/ig-publisher-scripts/branches
> 
> Let's avoid magic and go w/ `main`.

Fixed in https://github.com/FHIR/sushi/pull/720/commits/f35bee27611806d0f0425876df65f0359c2c27a2.

**Review by cmoesel — APPROVED** [review]
I initially found a bug in the scripts themselves, so I was waiting for HL7/ig-publisher-scripts#3 to get merged before approving and merging this.  It's merged so all looks good here too!

**Pull request merged**
