### PR TITLE
Warn when a slice element is accessed via numeric index

### LINKED ISSUE #1030: Warn when users access slices by numeric indices (or soft indexing)
SUSHI auto-populates _required_ slices into instances before processing any rules.  When users then write rules for the same array by number (or soft-index), then they may be accessing these pre-populated slice entries (intentionally or unintentionally).

It is much safer to write rules that call out the slices by name rather than using indices (which are subject to the order in which SUSHI has written the slices into the instance). So... SUSHI should warn users when they do this.

This ultimately helps lead us toward a situation in which we can more safely change how SUSHI handles slices and soft indexing.

See #1028 for one relevant example where this is a problem.

### PR DESCRIPTION
**Pull request by julianxcarter**
Fixes #1030, logging a warning when users access a slice using a numeric index. This warning is only logged when an array has it's slicing rules set to `closed` (in which case all elements in the array are slices by definition), or if the numeric index is determined to reference a slice that will be pre-loaded onto an instance as an implied property. A slice will be loaded automatically if it's cardinality indicates that it is required _and_ it contains a `pattern[x]` or `fixed[x]` value on itself or any of its children. 

This [FSH Online link](https://fshschool.org/FSHOnline/#/share/3ryTLXM) includes test cases.

### CODE REVIEW

**Review by mint-thompson — CHANGES_REQUESTED** [review]
It looks like the logic for `getPreloadedSlices` is similar to the logic in `setImpliedPropertiesOnInstance`. This makes sense to me, but there is a scenario which is not handled by `getPreloadedSlices`: when the Profile has a complex type as a fixed/pattern value on a slice, but the Instance of that Profile refers to an element within that complex type. This is an example:
```
Profile: UnusualQuestionnaire
Parent: Questionnaire
* contact ^slicing.discriminator[0].path = "name"
* contact ^slicing.discriminator[0].type = #value
* contact ^slicing.rules = #open
* contact contains bones 1..1
* contact[bones] = Cash4Bones

Instance: UnusualInstance
InstanceOf: UnusualQuestionnaire
* status = #in-progress
* item[0].linkId = "link id"
* item[0].type = #display
* contact[0].telecom[0].use = #work

Instance: Cash4Bones
InstanceOf: ContactDetail
Usage: #inline
* name = "someone suspicious"
* telecom[0].value = "1 800 cash 4 bones"
```

In `UnusualInstance`, the `contact[bones]` slice is referred to numerically, so a warning should be emitted. The warning _does_ get emitted correctly if the values on `contact[bones]` slices are defined individually, instead of by using the inline instance.

**Review by guhanthuran — APPROVED** [review]
Looks good to me - after implementing Mint's changes I think this is ready to go.

**Comment by julianxcarter** [comment]
> It looks like the logic for `getPreloadedSlices` is similar to the logic in `setImpliedPropertiesOnInstance`. This makes sense to me, but there is a scenario which is not handled by `getPreloadedSlices`: when the Profile has a complex type as a fixed/pattern value on a slice, but the Instance of that Profile refers to an element within that complex type.

Thank you for catching this, I hadn't thought of the possibility that a sliced element _itself_ could have a `fixed[x]` or `pattern[x]` value, and not just it's children. Commit [b98a8a9](https://github.com/FHIR/sushi/pull/1066/commits/b98a8a9d906e2f253a14374a91af044895a4d7a2) addresses this.

**Review by mint-thompson — APPROVED** [review]
Thank you! Hopefully this will encourage better authoring around slices.

**Review by guhanthuran — APPROVED** [review]
Looks good to me!

**Pull request merged**
