### PR TITLE
Use R5 5.0.0 for cross-version (implied) extensions

### PR DESCRIPTION
**Pull request by cmoesel**
When SUSHI builds virtual extensions to support cross-version (a.k.a. implied) extensions, it should use the official R5 package. Up until now, it has been using R5 current -- but now that R5 is released it should use R5 5.0.0.

This PR also updates all of the R5 fixtures to use the definitions from the official R5 release.

Fixes [CIMPL-1101](https://standardhealthrecord.atlassian.net/browse/CIMPL-1101).

### CODE REVIEW

**Review by mint-thompson — COMMENTED** [review]
Nothing to note other than what @jafeltra already pointed out. Thank you!

**Comment by cmoesel** [comment]
I thought I searched out all the `#current`, but now I see I missed a bunch. Thank you! I'm on it!

**Comment by cmoesel** [comment]
@jafeltra and @mint-thompson - thanks for the quick review! 19c309f fixes up the remaining #current references.

**Review by mint-thompson — APPROVED** [review]

**Review by mint-thompson — APPROVED** [review]

**Comment by cmoesel** [comment]
I'm going to go ahead and merge this with the one re-review approval (from @mint-thompson) since I addressed @jafeltra's previous comments. People are waiting on the v2 fix, so I want to get that rolling ASAP!

**Pull request merged**
