### PR TITLE
Contribution Policy

### PR DESCRIPTION
**Pull request by jafeltra**
This PR adds a Contribution Policy for SUSHI. This includes a `CONTRIBUTING.md` file and a `CODE-OF-CONDUCT.md` file.

The Code of Conduct comes from https://www.contributor-covenant.org/. They mentioned there is a badge, so I added it, but it isn't required. If you look at the branch in the main code viewer, you can see the badge in the README and see the top-level link that GitHub adds for the Code of Conduct at the top of the README viewer.

One other note: these files are both in the root of the repository, but I learned that you can alternatively add them to the `.github` directory. That's actually where the [github docs repo](https://github.com/github/docs/tree/main/.github) has these files. On one hand, it keeps these types of files all in one place. On the other hand, they're a little less discoverable. Let me know if anyone has an opinion on the placement.

### CODE REVIEW

**Comment by cmoesel** [comment]
Thanks, Julia. This looks great -- and I think that potential contributors will really appreciate it! I also like the Code of Conduct badge and tab.

As for the location of the files, I prefer having them in the root directory of the project so that others easily notice them. Up until today, I wouldn't have thought of looking in `.github` for files like this.

**Comment by jafeltra** [comment]
@cmoesel  and @mint-thompson: I made some small tweaks based on feedback from @KaelynJefferson. Let me know what you think.

Also, I just wanted to call out two other thoughts to make sure we had considered:

- The CONTRIBUTING document refers to "maintainers". Since there will be specific roles defined for the FSH project, if that term is overloaded now, I can update its use.
- We will need a contact for the CODE-OF-CONDUCT file for reporting issues. I left the placeholder for now, but we will need to update this to a real contact before we finalize this document.

**Comment by cmoesel** [comment]
@jafeltra HL7 has reviewed it and noted that we should use the [HL7 Code of Conduct](https://www.hl7.org/legal/code-of-conduct.cfm) instead of the one we're currently pointing to. Please:
* Update CONTRIBUTING to point to the HL7 Code of Conduct
* Update CODE-OF-CONDUCT to include a link to the HL7 Code of Conduct. Perhaps something as simple as:
  > To ensure a welcoming environment, we follow the [HL7 Code of Conduct](https://www.hl7.org/legal/code-of-conduct.cfm) and expect contributors to do the same. For your convenience, a copy of the HL7 Code of Conduct, as of June 2024, is included below. Please visit the official [HL7 Code of Conduct](https://www.hl7.org/legal/code-of-conduct.cfm) for the most recent version.
  >
  > (HL7 Code of Conduct text goes here...)

**Comment by cmoesel** [comment]
Just documenting what we discussed in our 1:1: It's sufficient to have the CODE-OF-CONDUCT file link to the HL7 Code of Conduct _without_ copying all its text.

**Comment by jafeltra** [comment]
@cmoesel - I just updated this PR with the feedback from HL7 and the approach you noted above.

**Review by cmoesel — APPROVED** [review]
This looks great. Thank you, @jafeltra. At this point you can add variations of these to the remaining repos:
* GoFSH
* FHIR Package Loader
* FSH Online
* FSH Online Examples
* FSH School Site
* FSH VS Code Extension

Thanks!
Chris

**Pull request merged**
