### PR TITLE
Ig data copy tweaks

### LINKED ISSUE #267: Need to preserve ignoreWarnings.txt if supplied
Running SUSHI doesn't transfer the contents to build

### PR DESCRIPTION
**Pull request by cmoesel**
Fixes #267 and #268.  See individual commits for details.

### CODE REVIEW

**Comment by ngfreiter** [comment]
@cmoesel As Travis is showing, this fails on windows. When changing the tests it looks like you introduced extra spaced which don't exist on the output:
image

**Comment by ngfreiter** [comment]
More specifically it looks like it is the line endings, passed if you change to `\r\n` like so: 
image

**Comment by cmoesel** [comment]
Ugh.

**Comment by cmoesel** [comment]
But if I switch it to that, then it will probably fail on Mac.  I'll probably have to do OS-specific line-endings.  Ugh.  Stand by.

**Pull request merged**
