### PR TITLE
Revise warning message for configuration "pages" property

### LINKED ISSUE #1308: Warning messages about unrecognized configuration properties under "pages" always suggest file type endings
https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/error.20message/near/376451856

```yaml
pages:
  deployment.md:
    Title: Deployment
```
The `title` property should be lowercase, so a warning is emitted. But, since the property path starts with `/pages`, SUSHI emits the warning message `Pages should end with .md, .xml, or .html.`. The property path will need to be checked more carefully to see if that warning message is appropriate.

### PR DESCRIPTION
**Pull request by mint-thompson**
Fixes #1308 and completes task [CIMPL-1144](https://standardhealthrecord.atlassian.net/browse/CIMPL-1144).

An unrecognized property within the "pages" property may or may not represent a subpage. Revise warning message to better acknowledge both possibilities.

### CODE REVIEW

**Review by cmoesel — DISMISSED** [review]
The new messages provide more guidance and allow for more of the possible reasons a user might get that error. Well done!

**Review by jafeltra — COMMENTED** [review]
Just had one small comment/conversation with myself. Let me know what you think.

**Review by cmoesel — APPROVED** [review]
Still good!

**Review by jafeltra — APPROVED** [review]
I love an Oxford comma, so this is great. Thanks!

**Pull request merged**
