### PR TITLE
Fix problem with contentReference and Logic Models

### PR DESCRIPTION
**Pull request by bkaney**
When unfolding a contentReference, include fishing for Logical Models. This resolves https://github.com/FHIR/sushi/issues/1328

### CODE REVIEW

**Comment by bkaney** [comment]
Hey @cmoesel  -- I agree there should be a test! But I'm not sure what that test is doing at first glance,.. maybe it would be most efficient if you or someone on your team too a crack at it?

**Comment by cmoesel** [comment]
Sure thing. I'll take a crack at it and push back to your branch (if it lets me).

**Comment by cmoesel** [comment]
OK. It was a little more complicated than I originally thought. But I wrote two tests. I didn't have permission to push to your branch, so I made a PR into your PR branch here: https://github.com/Vermonster/sushi/pull/1

**Comment by bkaney** [comment]
@cmoesel  -- okay, awesome your tests are part of this PR now!

**Comment by bkaney** [comment]
Thanks! the sql-on-fhir group really appreciates this moving forward!

**Pull request merged**
