### PR TITLE
New and improved regression

### PR DESCRIPTION
**Pull request by cmoesel**
Changes and improvements to the regression script, including:
- Implemented in TypeScript so it _hopefully_ works in Windows (@ngfreiter or @mint-thompson, please confirm)
- Downloads SUSHI versions to temp folders to increase speed of repeated runs (vs always using npx to download)
- Downloads repos as zips instead of cloning (to improve speed of getting repo source and remove git dependency)
- Supports specification of repo branch to use

This now works equally fast (more or less) whether using a SUSHI from NPM, from GitHub, or locally.  I also used lots of async calls in the script, again trying to gain as much efficiency as possible.  We're not fully leveraging it, however, as there are some loops I force to be synchronized (by using `for(x in y)` instead of `y.forEach(x)`.  This is partly because I think running more than one SUSHI in parallel could wreak havoc on the `.fhir` cache if 2 SUSHIs try to install a package at the same time (or if one detects the package as installed when it's not yet fully installed).  We _could_ allow the repo downloads and repo diff generation to all happen async in parallel, but for now, I'll save that for later.

By default `npm run regression` will use a select set of repos hand-chosen by me.  They represent some of our power users, but also represent some pre-1.0.0 repos.  On my system, it took just over 2 minutes to run regression on these 7 repos.  Running regression on all 52 repos took about 23 minutes (_saner_ is a beast and it has a fork too).

To test, use `npm run regression`, but also try a few other things out w/ `ts-node regression/run-regression.ts`.  I especially need at least one Windows tester.

### CODE REVIEW

**Comment by cmoesel** [comment]
Oh, note that you'll find that any repo using our menu feature will have a change -- because we apparently have a bug in our menu generation that it outputting the path wrong (in a comment), so there's always a diff on that since we store the two versions of the repo in different folders.  You'll know what I mean when you see it.

**Comment by mint-thompson** [comment]
When first running on a Windows 10 machine, the script unfortunately did not get very far:
```
Installing sushi#master from GitHub
Installing local sushi at C:\Users\mathompson\Documents\shr\sushi
Unexpected error:  Error: Command failed: npm install https://github.com/FHIR/sushi.git#master
npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mathompson\AppData\Roaming\npm-cache\_logs\2020-12-10T20_50_40_669Z-debug.log
```
I was able to resolve this by adding `C:\Program Files\Git\mingw64\libexec\git-core` to my PATH environment variable. This is something we will likely want to document.

After this, it started successfully, making it through the first five repos, but encountered a problem on the sixth:
```
Processing HL7NZ/hpi#master (6 of 7)
  - Downloading https://github.com/HL7NZ/hpi/archive/master.zip
Unexpected error:  [Error: EPERM: operation not permitted, symlink '..\handlebars\bin\handlebars' -> 'C:\Users\mathompson\Documents\shr\sushi\regression\output\HL7NZ-hpi-master\hpi-master\localscripts\node_modules\.bin\handlebars'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',
  path: '..\\handlebars\\bin\\handlebars',
  dest: 'C:\\Users\\mathompson\\Documents\\shr\\sushi\\regression\\output\\HL7NZ-hpi-master\\hpi-master\\localscripts\\node_modules\\.bin\\handlebars'
}
```
This one, I'm not so sure about how to start troubleshooting.

I should add, I got this successful run by running from the bash terminal inside VSCode. I get a very spicy looking error from the v8 engine when running from my normal bash terminal:
```
Running SUSHI regression with
  - repoFile: regression\repos-select.txt
  - version1: gh:master
  - version2: local
  - output:   regression\output

npm[15416]: c:\ws\src\node_file.cc:1699: Assertion `(argc) == (5)' failed.
 1: 00007FF6D265035F napi_wrap+119615
 2: 00007FF6D25F7666 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NextTableOffset+38102
 3: 00007FF6D25F79E1 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NextTableOffset+38993
 4: 00007FF6D25EAA66 v8::base::CPU::has_sse+12902
 5: 00007FF6D2DE8280 v8::internal::Builtins::builtin_handle+323456
 6: 00007FF6D2DE77C7 v8::internal::Builtins::builtin_handle+320711
 7: 00007FF6D2DE7B08 v8::internal::Builtins::builtin_handle+321544
 8: 00007FF6D2DE790E v8::internal::Builtins::builtin_handle+321038
 9: 00007FF6D3289A4D v8::internal::SetupIsolateDelegate::SetupHeap+547181
10: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
11: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
12: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
13: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
14: 00007FF6D3207B0C v8::internal::SetupIsolateDelegate::SetupHeap+14892
15: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
16: 00007FF6D3207B0C v8::internal::SetupIsolateDelegate::SetupHeap+14892
17: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
18: 00007FF6D323C465 v8::internal::SetupIsolateDelegate::SetupHeap+230277
19: 00007FF6D320E7DC v8::internal::SetupIsolateDelegate::SetupHeap+42748
20: 00007FF6D325DF02 v8::internal::SetupIsolateDelegate::SetupHeap+368162
21: 00007FF6D322B97D v8::internal::SetupIsolateDelegate::SetupHeap+161949
22: 00007FF6D320BBFC v8::internal::SetupIsolateDelegate::SetupHeap+31516
23: 00007FF6D2D279E0 v8::internal::Execution::CallWasm+1536
24: 00007FF6D2D27AD3 v8::internal::Execution::CallWasm+1779
25: 00007FF6D2D27EB2 v8::internal::Execution::TryCall+354
26: 00007FF6D2D09DA5 v8::internal::MicrotaskQueue::RunMicrotasks+501
27: 00007FF6D2672CB0 node::CallbackScope::~CallbackScope+672
28: 00007FF6D26730AC node::CallbackScope::~CallbackScope+1692
29: 00007FF6D266B1E5 v8::internal::compiler::Operator::EffectOutputCount+229
30: 00007FF6D25EDD43 v8::base::CPU::has_sse+25923
31: 00007FF6D25E2634 v8::internal::RegExpMacroAssemblerX64::stack_limit_slack+224116
32: 00007FF6D26A5D57 uv_timer_stop+775
33: 00007FF6D26A25BB uv_async_send+331
34: 00007FF6D26A1D3C uv_loop_init+1276
35: 00007FF6D26A1EEC uv_run+220
36: 00007FF6D25ADA21 v8::internal::RegExpMacroAssemblerX64::stack_limit_slack+8033
37: 00007FF6D2621B75 node::Start+293
38: 00007FF6D2486A9C RC4_options+340380
39: 00007FF6D3341A38 v8::internal::SetupIsolateDelegate::SetupHeap+1300824
40: 00007FFCC53C7C24 BaseThreadInitThunk+20
41: 00007FFCC736D4D1 RtlUserThreadStart+33
```

As for running from a cmd window... I didn't have high hopes for that to begin with, but the error is a pretty understandable one, at least:
```
Installing sushi#master from GitHub
Installing local sushi at C:\Users\mathompson\Documents\shr\sushi
Unexpected error:  Error: Command failed: npm install
'rm' is not recognized as an internal or external command,
operable program or batch file.
```

PowerShell gives an identical error.

**Comment by cmoesel** [comment]
Thank you, @mint-thompson!  It's disappointing, but thank you anyway. ;-)

Regarding `npm install https://github.com/FHIR/sushi.git#master` failing...  Did you try running that command locally and it failed then too?  I'm just trying to figure out if it's only bad inside the TypeScript execution, or if it's bad under normal circumstances too?  According to [npm install docs](https://docs.npmjs.com/cli/v6/commands/npm-install) that command _should_ work.  But... there is another way I can do it if need be (it's just a little more complicated).

As for the error w/ the 6th repo... that's weird.  It looks like maybe that repo actually contains a symlink?  Or the symlink is somehow bad on your system (as I note that `sushi\regression\output\HL7NZ-hpi-master\hpi-master` certainly isn't anywhere near a valid path on my system, regardless of path separators). If it's something specific to that repo, we can swap out that repo for a different one.  I'm curious though -- did it crash at that point or keep going?  My error handling is probably not the best in the script right now...

And the bash terminal... _sigh_.  I am perplexed why it would work in your VS Code bash terminal but not your native one.  I kind of assumed VS Code wrapped your native bash anyway (that's how it seems to work on Mac).

**Comment by mint-thompson** [comment]
`npm install https://github.com/FHIR/sushi.git#master` worked fine as its own command in cmd and PowerShell. `rm rf` is the first part of the build script, so that's my guess as to what actually was happening when it broke.

The error on the sixth repo did cause a crash at that point. The regression script did not start any actions on the seventh repo.

**Comment by cmoesel** [comment]
@mint-thompson -- I just pushed some fixes that should hopefully make things better on windows:
* Don't use `npm install https://github.com/..." to install from GitHub.  Instead, download the SUSHI source and install locally.  This should hopefully make it so you don't need to put that extra git lib on your path.
* Use `fs.emptyDir` instead of `fs.rmdirSync` to recursively remove `output` contents.  Hopefully this resolves the bash crash.
* Replace the 6th repo in the select repos w/ a different one that hopefully doesn't have problematic symlinks.

Can you give it a try again?

**Comment by mint-thompson** [comment]
@cmoesel Excellent news! These latest updates have improved the results.
- When running from my VSCode bash, the script completes successfully. Upon completion, it opens the report summary in my browser.
- Turns out the bash used by VSCode and the one I had a shortcut for in windows were different executables. Specifically, VSCode was using `C:\Program Files\Git\bin\bash.exe` and my desktop shortcut was opening up `C:\Program Files\Git\git-bash.exe`. So, I guess I just have one useful and one less-useful version of bash on my system? I'm willing to call that a configuration issue on my end.
- Same results as earlier in cmd and PowerShell.

**Comment by cmoesel** [comment]
Thanks, @mint-thompson!  I'm afraid that the `cmd` and `PowerShell` issues may be difficult to debug/resolve -- but I'm going to try one more thing.  I'll let you know when it's pushed.  Thanks for your help with this!

**Comment by cmoesel** [comment]
Hey @mint-thompson -- I tried one more thing that may or may not make a difference.  It turns out that using `execFile` rather than `exec` is considered safer anyway -- so whether or not it works w/ cmd/powershell, it's an improvement any.

Can you try one more time?  And also make sure it didn't break anything that previously worked?

**Comment by cmoesel** [comment]
I'll try that!  With that change did it also work in `cmd` and `Powershell` or is that still broken anyway?

**Comment by cmoesel** [comment]
OK.  Pushed.

**Comment by mint-thompson** [comment]
Still doesn't work in cmd or PowerShell (since that's getting tripped up on `rm rf` in our install + build process), but it is back to working in bash. Which I guess means that `npm build` has probably never worked from cmd? That may or may not be something we want to solve, but is a bit outside the scope of the regression script.

**Comment by cmoesel** [comment]
Ohhhhhhh.... I see.  It's our script in `package.json` that's causing the problem.  I get it now!  Agreed, that's probably a different problem for a different day, but I think it should be pretty easily fixable actually.

**Comment by cmoesel** [comment]
@mint-thompson -- I was in a meeting so I multi-tasked to go ahead and fix the remaining issue w/ the npm script in windows.  Do you mind giving it just one more try?

**Comment by mint-thompson** [comment]
The build script now runs successfully in both cmd and PowerShell! So, every version of SUSHI starting with the one that includes this should work with the regression script in cmd and PowerShell. With that, the windows-specific issues are completely solved. Thank you!

**Comment by cmoesel** [comment]
Woohoo!

**Review by mint-thompson — APPROVED** [review]

**Review by jafeltra — APPROVED** [review]
This looks good to me! It ran successfully for me (although I haven't let it run for all the repos in `repos-all.txt` yet, but I can if you feel like I should). I also appreciate the change to support the non SSH cloning!

**Pull request merged**
